### PR TITLE
First steps to decrease coupling between modbus register and graph

### PR DESCRIPTION
**Pull request by jgeudens**
This MR will replace the register address with a custom function (for example ~~`REG(49001)`~~) in the expression field.

The main improvement will be a looser coupling between graph and registers addresses. The goal is to allow expressions with values from multiple register addresses (for example ~~`REG(49001) + REG(49002)`~~).

The end user will then have a more generic interface to convert raw data from an embedded target to human readable data in the graph.

## Tasks and use cases
* [x] Remove limitation of duplicate register/expressions (register dialog + import mbc)
* [x] Replace register address with ~~`REG([register])`~~ in expression
* [x] Import MBC => ~~`REG([register])`~~
* [ ] Import older mbs with VAL => **moved to other MR**
* [x] Multiple REG([register]) in one graph expression
* [x] Make sure logging works when no ~~REG([register])~~ is specified in the expressions

### CODE REVIEW

**Comment by jgeudens** [comment]
@ben-edna @pluyckx:
What do you think about the `REG(40001)` syntax? I'm pondering that MB_REG might be better. Or maybe MB_HOLDING because we are reading modbus holding registers (40001 range).

**Comment by jgeudens** [comment]
@ben-edna : I have been thinking about the way to include the registers in the expression. @pluyckx mentioned that a function name might be quite long. A function call also uses parenthesis. This might be confusing with other parenthesis in the expression. The connection id and 32-bit indicator is also specific to the register, so this should be part of the register definition in the expression. I have also done some experiments with the parser library and noticed some pitfalls. A function is more difficult to implement. The function will also be shared over all instances of the parser.

So a function call doesn't seem a good choice.

A possible alternative might be a syntax similar to bash variable expansion.

Something like:
```
Normal 16 bit register: ${40001}
32 bit register: ${40001: 32}
Connection 2: ${40001: 2}
32 bit register on connection 2: ${40001: 2, 32}
```

Side note is that the connection of connection is limited to 31.

What do you think?

**Comment by ben-edna** [comment]
My proposal would be to use more expressive statements instead of raw numbers, this would give more flexibility in the future

```
${REG[@CONN][:TYPE]}  <--- Format
${45332@2:32b}  <--- Connection + type
${45332@2} <-- no type (defaults to unsigned 16-bit)
${45332:32b} <-- without connection (but unsigned 32-bit)
${45332:s32b} <-- could support signed 32-bit
${45332} <-- regular 16-bit unsigned holding register at first connection
```

This way you could support
```
16b
u16b
s16b
32b
u32b
s32b
f32
f64
```

In the future more exotic types could be introduced such as masking or partial registers for bitfields

**Comment by spoorcc** [comment]
:tada:

**Pull request merged**
