### PR TITLE
little problem with strucs

### PR DESCRIPTION
**Pull request by Ali-Kazzazi**
some of the structs didn't have the correct syntax.

### CODE REVIEW

**Comment by jgeudens** [comment]
Thank you for your interest in ModbusScope.

But I fail to see how your change improves the code. The initialization of the structs is valid C++ syntax and is verified to work. Maybe you can explain your reasoning a bit more?

**Comment by aghk73** [comment]
There was compile error in structs for example in this cpp file in this directory [src/communication/modbusmaster.cpp].
I changed this:
` 
struct ModbusConnection::SerialSettings serialSettings =
            {
                .portName = _pSettingsModel->portName(_connectionId),
                .parity = _pSettingsModel->parity(_connectionId),
                .baudrate = _pSettingsModel->baudrate(_connectionId),
                .databits = _pSettingsModel->databits(_connectionId),
                .stopbits = _pSettingsModel->stopbits(_connectionId),
            };`

to this:
`
ModbusConnection::SerialSettings serialSettings;

                serialSettings.portName = _pSettingsModel->portName(_connectionId);
                serialSettings.parity = _pSettingsModel->parity(_connectionId);
                serialSettings.baudrate = _pSettingsModel->baudrate(_connectionId);
                serialSettings.databits = _pSettingsModel->databits(_connectionId);
                serialSettings.stopbits = _pSettingsModel->stopbits(_connectionId);`

just the structs syntax, nothing else.

**Comment by jgeudens** [comment]
Hmm, strange. What compiler did you use? Which version?

**Comment by pluyckx** [comment]
@aghk73, make sure your compiler supports c++20: [https://en.cppreference.com/w/cpp/language/aggregate_initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization).
It seems aggregate initialization is a c++20 feature.

**Comment by aghk73** [comment]
first of all, thank you so much, that is my first fork and pull request in GitHub and that was a great experience for me.
I use MSVC2019 64bit and Qt version 5.15.2.

**Comment by jgeudens** [comment]
I use mingw81_64 that is provided by the Qt installer on Windows. And the default gcc compiler installed on my Ubuntu.

Since @pluyckx mentions that this is a C++20 feature, maybe we should set the correct C++ standard in the CMakeList.

https://github.com/jgeudens/ModbusScope/blob/996cf6df34fb797bb6fbe6e33c9fa10de0fc388a/CMakeLists.txt#L9

@aghk73 : Can you test if it works with your compiler when you set it to 20?

**Comment by jgeudens** [comment]
C++ standard is updated in d035c9fe87d6231fd745b258b3bdfec8375cb6dc

**Pull request closed without merging**
